name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  provider: ^6.1.1
  get_it: ^7.6.4
  flutter_lints: ^5.0.0
  intl: ^0.18.1
  http: ^0.13.5
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^4.0.1
  mocktail: ^0.3.0
  retry: ^3.1.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "icon_cat.png"